//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandomMenuAdvisor.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FoodData", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary.Model")]
    [System.SerializableAttribute()]
    public partial class FoodData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FoodNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryName {
            get {
                return this.CategoryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryNameField, value) != true)) {
                    this.CategoryNameField = value;
                    this.RaisePropertyChanged("CategoryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FoodName {
            get {
                return this.FoodNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FoodNameField, value) != true)) {
                    this.FoodNameField = value;
                    this.RaisePropertyChanged("FoodName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IMenuAdvisor")]
    public interface IMenuAdvisor {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuAdvisor/DatabaseConnectionTest", ReplyAction="http://tempuri.org/IMenuAdvisor/DatabaseConnectionTestResponse")]
        void DatabaseConnectionTest();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuAdvisor/DatabaseConnectionTest", ReplyAction="http://tempuri.org/IMenuAdvisor/DatabaseConnectionTestResponse")]
        System.Threading.Tasks.Task DatabaseConnectionTestAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuAdvisor/GetRandomRequestedData", ReplyAction="http://tempuri.org/IMenuAdvisor/GetRandomRequestedDataResponse")]
        System.Data.DataTable GetRandomRequestedData(int data_length);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuAdvisor/GetRandomRequestedData", ReplyAction="http://tempuri.org/IMenuAdvisor/GetRandomRequestedDataResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetRandomRequestedDataAsync(int data_length);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuAdvisor/GetCategoryData", ReplyAction="http://tempuri.org/IMenuAdvisor/GetCategoryDataResponse")]
        System.Data.DataTable GetCategoryData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuAdvisor/GetCategoryData", ReplyAction="http://tempuri.org/IMenuAdvisor/GetCategoryDataResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetCategoryDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuAdvisor/GetFoodData", ReplyAction="http://tempuri.org/IMenuAdvisor/GetFoodDataResponse")]
        System.Data.DataTable GetFoodData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuAdvisor/GetFoodData", ReplyAction="http://tempuri.org/IMenuAdvisor/GetFoodDataResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetFoodDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuAdvisor/GetPercentageData", ReplyAction="http://tempuri.org/IMenuAdvisor/GetPercentageDataResponse")]
        System.Data.DataTable GetPercentageData(string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuAdvisor/GetPercentageData", ReplyAction="http://tempuri.org/IMenuAdvisor/GetPercentageDataResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetPercentageDataAsync(string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuAdvisor/GetRandomResult", ReplyAction="http://tempuri.org/IMenuAdvisor/GetRandomResultResponse")]
        RandomMenuAdvisor.ServiceReference1.FoodData GetRandomResult();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuAdvisor/GetRandomResult", ReplyAction="http://tempuri.org/IMenuAdvisor/GetRandomResultResponse")]
        System.Threading.Tasks.Task<RandomMenuAdvisor.ServiceReference1.FoodData> GetRandomResultAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMenuAdvisorChannel : RandomMenuAdvisor.ServiceReference1.IMenuAdvisor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MenuAdvisorClient : System.ServiceModel.ClientBase<RandomMenuAdvisor.ServiceReference1.IMenuAdvisor>, RandomMenuAdvisor.ServiceReference1.IMenuAdvisor {
        
        public MenuAdvisorClient() {
        }
        
        public MenuAdvisorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MenuAdvisorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MenuAdvisorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MenuAdvisorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DatabaseConnectionTest() {
            base.Channel.DatabaseConnectionTest();
        }
        
        public System.Threading.Tasks.Task DatabaseConnectionTestAsync() {
            return base.Channel.DatabaseConnectionTestAsync();
        }
        
        public System.Data.DataTable GetRandomRequestedData(int data_length) {
            return base.Channel.GetRandomRequestedData(data_length);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetRandomRequestedDataAsync(int data_length) {
            return base.Channel.GetRandomRequestedDataAsync(data_length);
        }
        
        public System.Data.DataTable GetCategoryData() {
            return base.Channel.GetCategoryData();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetCategoryDataAsync() {
            return base.Channel.GetCategoryDataAsync();
        }
        
        public System.Data.DataTable GetFoodData() {
            return base.Channel.GetFoodData();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetFoodDataAsync() {
            return base.Channel.GetFoodDataAsync();
        }
        
        public System.Data.DataTable GetPercentageData(string category) {
            return base.Channel.GetPercentageData(category);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetPercentageDataAsync(string category) {
            return base.Channel.GetPercentageDataAsync(category);
        }
        
        public RandomMenuAdvisor.ServiceReference1.FoodData GetRandomResult() {
            return base.Channel.GetRandomResult();
        }
        
        public System.Threading.Tasks.Task<RandomMenuAdvisor.ServiceReference1.FoodData> GetRandomResultAsync() {
            return base.Channel.GetRandomResultAsync();
        }
    }
}
